imagens = [
    {"nome":"ISIC_0024468.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0024470.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0024707.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0024763.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0024771.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0024800.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0024913.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0024948.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0025780.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0025953.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0025957.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0025992.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026149.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026171.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026457.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026525.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026575.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026625.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026626.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026702.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026709.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026729.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026848.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026857.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026905.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0027172.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0027254.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0027447.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0027536.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0027562.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0027588.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0027615.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0027650.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0027829.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0027884.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0027950.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0028063.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0028076.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0028190.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0028314.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0028370.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0028393.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0028517.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0028558.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0028619.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0028854.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0028941.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0028990.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029041.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029133.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029141.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029309.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029460.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029500.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029659.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029713.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029827.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029830.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029840.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029900.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029930.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0030133.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0030142.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0030344.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0030408.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0030463.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0030655.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0030730.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0030825.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0030877.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0031040.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0031108.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0031228.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0031292.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0031335.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0031381.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0031430.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0031506.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0031922.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0032135.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0025803.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0025825.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026040.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026194.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026212.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026468.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026650.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0026984.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0027452.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0027580.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0027802.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0027896.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0028820.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029025.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029210.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029781.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0029915.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0030036.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0030143.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"ISIC_0030242.jpg", "doencas":["Ceratose Actínica"]},
    {"nome":"1_14.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_15.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_16.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_17.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_18.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_19.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_20.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_21.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_22.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_23.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_24.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_25.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_26.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_27.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_29.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_30.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_31.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_32.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_35.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_36.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_39.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_41.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_42.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_43.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_44.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_45.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_46.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_47.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_48.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_49.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_51.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_52.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_53.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_55.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_57.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_58.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_59.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_60.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_62.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_63.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_64.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_66.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_67.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_68.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_69.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_71.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_73.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_74.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_76.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_77.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_78.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_79.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_80.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_81.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_82.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_83.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_84.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_0.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_1.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_10.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_11.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_12.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_13.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_15.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_17.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_18.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_19.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_2.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_20.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_21.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_22.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_23.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_24.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_25.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_27.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_4.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_5.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_6.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_7.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_8.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"2_9.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_14.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_15.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_16.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_17.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_18.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_19.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_20.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_23.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_24.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_25.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_26.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_27.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_29.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_30.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_35.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_36.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_39.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_41.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_42.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_43.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"1_44.jpg", "doencas":["Dermatite Atópica"]},
    {"nome":"ISIC_0014567_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014568_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014569_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014571_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014572_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014573_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014574_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014575_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014576_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014577_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014578_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014581_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014585_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014586_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014587_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014588_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014589_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014592_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014593_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014594_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014595_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014596_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014597_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014598_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014599_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014600_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014601_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014602_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014606_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014607_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014608_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014610_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014611_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014612_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014615_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014616_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014618_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014620_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014623_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014624_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014625_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014626_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014628_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014629_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014630_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014631_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014632_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014634_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014635_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014636_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014637_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014638_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014639_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014640_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014642_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014643_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014644_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014646_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014647_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014648_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014650_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014652_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014654_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014711_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014712_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014723_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014770_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014793_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014804_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014806_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014811_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014819_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014823_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014831_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0015006_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0015032_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0015044_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0015062_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0015112_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0015113_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014603_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014605_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014609_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014613_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014617_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014619_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014621_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014622_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014627_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014633_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014641_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014649_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014651_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0014653_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0015038_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0015108_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0015170_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0015220_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0015233_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0015260_downsampled.jpg", "doencas":["Verruga Seborreica"]},
    {"nome":"ISIC_0024318.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0024386.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0024396.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0024553.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0024845.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0025223.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0025302.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0025314.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0025373.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0025504.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0025594.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0025622.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0025668.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0025771.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0025903.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0025911.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0025954.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0025980.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0026417.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0026471.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0026629.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0027008.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0027044.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0027107.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0027118.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0027141.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0027188.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0027488.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0027598.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0027613.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0027727.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0027745.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0027876.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0028346.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0028651.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0028735.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0028790.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0028880.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0028926.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0029052.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0029130.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0029177.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0029248.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0029783.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0029891.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0029962.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0029973.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0030011.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0030015.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0030021.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0030244.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0030321.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0030579.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0030665.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0030757.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0030830.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0030870.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0031002.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0031123.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0031257.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0031271.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0031309.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0031344.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0031358.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0031372.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0031429.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0031735.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0031799.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0031827.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0032114.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0032138.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0032247.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0032410.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0032468.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0032613.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0032941.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0033005.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0033256.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0033422.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0033554.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0024330.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0024973.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0024994.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0025154.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0026254.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0026313.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0026473.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0026789.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0027216.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0027626.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0027648.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0029039.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0029297.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0029578.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0029760.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0029824.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0029967.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0030442.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0030555.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0031443.jpg","doencas":["Dermatofibra"]},
    {"nome":"ISIC_0000000.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000003.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000006.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000007.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000008.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000009.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000010.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000011.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000012.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000014.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000018_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000021_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000023_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000024_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000027_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000028_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000037_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000039_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000041_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000042_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000044_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000047_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000048_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000050_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000051_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000052_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000053_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000055_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000059_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000060_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000061_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000063_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000064_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000066.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000067.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000068.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000069.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000072.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000073.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000079_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000081_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000082_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000085_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000086_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000087_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000088_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000089_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000091_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000092_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000094_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000095_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000096_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000098_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000099_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000100_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000102_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000103_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000104_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000105_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000107_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000108_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000109_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000110_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000111_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000112_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000116_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000117_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000119_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000120_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000121_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000122_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000126_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000127_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000129_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000130_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000131_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000132_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000133_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000134_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000136_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000001.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000015.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000016.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000017_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000019_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000020_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000025_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000032_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000034_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000038_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000045_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000057_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000058_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000062_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000065_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000071.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000075.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000093_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000097_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0000101_downsampled.jpg","doencas":["Nevo Melanocítico"]},
    {"nome":"ISIC_0024329.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024372.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024418.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024463.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024517.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024522.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024539.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024562.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024575.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024579.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024710.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024925.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025069.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025089.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025130.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025178.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025182.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025264.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025319.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025331.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025350.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025358.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025411.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025471.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025539.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025577.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025637.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025696.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025790.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025808.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025811.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025831.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026014.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026083.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026100.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026138.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026152.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026203.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026319.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026388.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026411.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026466.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026492.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026549.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026645.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026720.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026872.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026927.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026992.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027047.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027084.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027178.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027184.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027231.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027343.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027506.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027529.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027550.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027577.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027678.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027700.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027719.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027767.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027930.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0028132.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0028158.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0028224.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0028231.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0028232.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0028335.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0028372.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0028381.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0028499.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0028644.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0028659.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0028730.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0028763.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0028816.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0028872.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0029043.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024450.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024843.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024923.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024946.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025029.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025196.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025247.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025712.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0025948.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026132.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026178.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026206.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026327.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026362.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026522.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0026981.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027303.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027708.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027753.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0027795.jpg","doencas":["Carcinoma de Células Escamosas"]},
    {"nome":"ISIC_0024370.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0024402.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0024475.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0024662.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0024669.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0024904.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025197.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025244.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025249.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025250.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025321.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025425.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025452.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025578.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025596.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025599.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025606.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025612.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025680.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025707.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025873.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0026068.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0026092.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0026163.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0026336.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0026349.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0026393.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0026467.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0026490.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0026693.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0027159.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0027210.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0027256.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0027269.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0027385.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0027522.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0027563.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0027665.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0027672.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0027856.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0027888.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0027903.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0027937.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0028188.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0028431.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0028680.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0028885.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0029099.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0029404.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0029439.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0029448.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0029486.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0029514.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0029877.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0029889.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0030070.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0030104.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0030283.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0030606.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0030722.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0030770.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0030882.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0030956.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031065.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031090.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031093.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031201.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031215.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031217.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031270.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031276.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031346.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031648.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031706.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031719.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031759.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031901.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031950.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031955.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031996.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0024375.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0024706.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0024747.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0024867.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025628.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025677.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0025807.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0026713.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0026876.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0027983.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0028146.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0028163.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0028406.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0028714.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0029608.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0029742.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031103.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0031197.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0032545.jpg","doencas":["Lesão Vascular"]},
    {"nome":"ISIC_0033991.jpg","doencas":["Lesão Vascular"]},
]

listaPastas = [
        {"nome":"Ceratose Actínica",
     "sigla":"Ceratose Actínica",
     "numero": 0},
        {"nome":"Dermatite Atópica",
     "sigla":"Dermatite Atópica",
     "numero": 1},
        {"nome":"Verruga Seborreica",
     "sigla":"Verruga Seborreica",
     "numero": 2},
        {"nome":"Dermatofibra",
     "sigla":"Dermatofibra",
     "numero": 3},
        {"nome":"Nevo Melanocítico",
     "sigla":"Nevo Melanocítico",
     "numero": 4},
        {"nome":"Carcinoma de Células Escamosas",
     "sigla":"Carcinoma de Células Escamosas",
     "numero": 5},
        {"nome":"Lesão Vascular", #1431
     "sigla":"Lesão Vascular",
     "numero": 6}
]

listaPastas2 = [
        {"nome":"Ceratose Actínica",
     "sigla":"Ceratose Actínica",
     "numero": 0},
        {"nome":"Dermatite Atópica",
     "sigla":"Dermatite Atópica",
     "numero": 1},
        {"nome":"Verruga Seborreica",
     "sigla":"Verruga Seborreica",
     "numero": 2},
        {"nome":"Dermatofibra",
     "sigla":"Dermatofibra",
     "numero": 3},
        {"nome":"Nevo Melanocítico",
     "sigla":"Nevo Melanocítico",
     "numero": 4},
        {"nome":"Carcinoma de Células Escamosas",
     "sigla":"Carcinoma de Células Escamosas",
     "numero": 5},
        {"nome":"Lesão Vascular",
     "sigla":"Lesão Vascular",
     "numero": 6}
]

import os
import shutil
import random

# Defina a proporção desejada para treinamento, teste e validação
train_ratio = 0.7
test_ratio = 0.15
val_ratio = 0.15

# Crie uma pasta para cada conjunto
source_dir = "imagens"
train_dir = "train"
test_dir = "test"
val_dir = "val"
os.makedirs(train_dir, exist_ok=True)
os.makedirs(test_dir, exist_ok=True)
os.makedirs(val_dir, exist_ok=True)

# Crie pastas para cada classe em cada conjunto
for pasta in listaPastas:
    folder_name = f"{pasta['sigla']}"
    os.makedirs(os.path.join(train_dir, folder_name), exist_ok=True)
    os.makedirs(os.path.join(test_dir, folder_name), exist_ok=True)
    os.makedirs(os.path.join(val_dir, folder_name), exist_ok=True)

# Separe as imagens em conjuntos
for pasta in listaPastas:
    classe = pasta['sigla']
    imagens_classe = [imagem for imagem in imagens if classe in imagem["doencas"]]
    random.shuffle(imagens_classe)
    total_imagens = len(imagens_classe)
    
    train_split = int(train_ratio * total_imagens)
    test_split = int(test_ratio * total_imagens)
    
    train_set = imagens_classe[:train_split]
    test_set = imagens_classe[train_split:(train_split + test_split)]
    val_set = imagens_classe[(train_split + test_split):]
    
    for imagem in train_set:
        src_file = os.path.join(source_dir, imagem["nome"])
        dest_folder = os.path.join(train_dir, classe)
        shutil.copy2(src_file, dest_folder)
    
    for imagem in test_set:
        src_file = os.path.join(source_dir, imagem["nome"])
        dest_folder = os.path.join(test_dir, classe)
        shutil.copy2(src_file, dest_folder)
    
    for imagem in val_set:
        src_file = os.path.join(source_dir, imagem["nome"])
        dest_folder = os.path.join(val_dir, classe)
        shutil.copy2(src_file, dest_folder)
